AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 80

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: true
  AllowSafeAssignment: true

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 25
  IgnoredMethods: []
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Naming/FileName:
  Exclude:
    - "lib/tty-pie.rb"

Style/AccessorGrouping:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/IfUnlessModifier:
    Enabled: false

Style/LambdaCall:
  SupportedStyles:
  - call
  - braces

Style/NegatedIf:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  Enabled: false
