---
language: ruby
sudo: false
cache: bundler
before_install: "gem install bundler -v '< 2'"
script: "bundle exec rake ci"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
  - jruby-9.1.5.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.5.0
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
